apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  labels:
    app: backend

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:

      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}

      containers:
      - name: backend

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - name: http
          containerPort: {{ .Values.container.port }}
          protocol: TCP

        envFrom:
        - configMapRef:
            name: backend-config

        - secretRef:
            name: backend-secret

        readinessProbe:
          tcpSocket:
            port: {{ .Values.container.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

        livenessProbe:
          tcpSocket:
            port: {{ .Values.container.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        resources:
          requests:
            cpu: 100m
            memory: 128Mi

          limits:
            cpu: 500m
            memory: 512Mi
